name: Update All Matches

on:
  schedule:
    - cron: "0 22 * * *" # JST 7:00
  workflow_dispatch:

jobs:
  update-all:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Set Secrets as Environment Variables
        run: |
          echo "FIREBASE_PRIVATE_KEY_JSON_BASE64=${{ secrets.FIREBASE_ADMIN_BASE64 }}" >> $GITHUB_ENV
          echo "DISCORD_WEBHOOK_MATCHES=${{ secrets.DISCORD_WEBHOOK_MATCHES }}" >> $GITHUB_ENV
          echo "DISCORD_WEBHOOK_JLEAGUE=${{ secrets.DISCORD_WEBHOOK_JLEAGUE }}" >> $GITHUB_ENV
          echo "DISCORD_WEBHOOK_CELTIC=${{ secrets.DISCORD_WEBHOOK_CELTIC }}" >> $GITHUB_ENV

      - name: Run updateJleagueSchedule script
        run: node --loader ts-node/esm scripts/updateJleagueSchedule.mts

      - name: Run updateCelticSchedule script
        run: node --loader ts-node/esm scripts/updateCelticSchedule.mts

      - name: Run updateCurrentMonthMatch script
        run: node --loader ts-node/esm scripts/updateCurrentMonthMatch.mts

      - name: Run mergeMatches script
        run: node --loader ts-node/esm scripts/mergeMatches.mts

      - name: Commit merged match data
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add src/data/current_month_matches.json \
                  src/data/current_month_matches_jleague.json \
                  src/data/current_month_matches_celtic.json \
                  src/data/current_month_matches_oversea.json \
                  src/data/updated_log.json
          git commit -m "🗂️ Auto update & merge match data" || echo "No changes"
          git push origin master || echo "No changes to push"
