name: Update Teams Meta

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 1 8 *' # 毎年8月1日 12:00 JST

jobs:
  update-teams-meta:
    runs-on: ubuntu-latest

    env:
      FOOTBALL_DATA_API_KEY: ${{ secrets.FOOTBALL_DATA_API_KEY }}
      API_FOOTBALL_KEY: ${{ secrets.API_FOOTBALL_KEY }}
      DISCORD_WEBHOOK_TEAMS: ${{ secrets.DISCORD_WEBHOOK_TEAMS }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run updateTeamsMeta.mts
        run: |
          node --loader ts-node/esm ./scripts/updateTeamsMeta.mts

      - name: Commit and push updated files
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add src/data/team_league_names.json src/data/updated_log.json
          git commit -m "auto: update team_league_names.json"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
