name: Update Celtic Schedule

on:
  schedule:
    - cron: '0 22 * * *' # JST 7:00（UTCでは前日の22:00）
  workflow_dispatch:

jobs:
  update-celtic:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm ci

      - name: Run updateCelticSchedule.mts
        env:
          FIREBASE_PRIVATE_KEY_JSON_BASE64: ${{ secrets.FIREBASE_PRIVATE_KEY_JSON_BASE64 }}
          DISCORD_WEBHOOK_CELTIC: ${{ secrets.DISCORD_WEBHOOK_CELTIC }}
        run: node --loader ts-node/esm scripts/updateCelticSchedule.mts
